name: release
on:
  push:
    tags:
      - v*
      - default

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release:
    name: Build on Push Tag 🚀
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r16b

      - name: Setup Go Environment
        uses: actions/setup-go@master

      - name: Build Libraries
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          BUILD_MACHINE: linux
        run: |
          echo NDK path is $NDK_HOME
          make -e

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
