name: test
on: [ push, pull_request ]

jobs:
  test_ubuntu:
    name: Run Make Test on Ubuntu 🧪
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Setup Go Environment
        uses: actions/setup-go@master
        with:
          go-version: '1.22'

      - name: Run Go Test
        run: go test $(go list ./...)

      - name: Test Build
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          BUILD_MACHINE: linux
          GC: go
        run: |
          echo NDK path is $NDK_HOME
          make -e

      - name: Build and Run Tests
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          BUILD_MACHINE: linux
          GOARCH: amd64
          GC: go
        run: |
          make -e install
          make -e runtest
